{{- if .Values.routing.inferencepool.create }}
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferencePool
metadata:
  name: {{ include "llm-d-modelservice.fullname" . }}-inference-pool
  namespace: {{ .Release.Namespace }}
spec:
  extensionRef:
    failureMode: FailClose
    group: ""
    kind: Service
    {{- if .Values.routing.inferencepool.eppService }}
    name: {{ .Values.routing.inferencepool.eppService }}
    {{- else }}
    name: {{ include "llm-d-modelservice.fullname" . }}-epp-service
    {{- end }}
  selector:
    {{- if .Values.multinode }}
    leaderworkerset.sigs.k8s.io/worker-index: "0"
    {{- end }}
    {{- include "llm-d-modelservice.pdlabels" . | nindent 4 }}
  targetPortNumber: {{ .Values.routing.servicePort }}
{{- end }}
