{{- /* Routing templates: InferencePool and HttpRoute */}}
{{- if and .Values.inferencePool .Values.endpointPicker }}
apiVersion: inference.networking.x-k8s.io/v1alpha2
kind: InferencePool
metadata:
  name: {{ include "llm-d-modelservice.fullname" . }}-inference-pool
  namespace: {{ .Release.Namespace }}
spec:
  extensionRef:
    failureMode: FailClose
    group: ""
    kind: Service
    name: {{ include "llm-d-modelservice.fullname" . }}-epp-service
  selector:
    {{- if .Values.multinode }}
    leaderworkerset.sigs.k8s.io/worker-index: "0"
    {{- end }}
    {{- include "llm-d-modelservice.pdlabels" . | nindent 4 }}
  targetPortNumber: {{ .Values.routing.servicePort }}
{{- end }}
---
{{- if and .Values.httpRoute .Values.inferencePool .Values.endpointPicker }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "llm-d-modelservice.fullname" . }}-http-route
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llm-d-modelservice.labels" . | nindent 4 }}
spec:
  {{- with .Values.routing.parentRefs }}
  parentRefs:
  {{- . | toYaml | nindent 2}}
  {{- end }}
  rules:
  - backendRefs:
    - group: inference.networking.x-k8s.io
      kind: InferencePool
      name: {{ include "llm-d-modelservice.fullname" . }}-inference-pool
      port: {{ .Values.routing.servicePort  }}
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
      headers:
      - name: x-model-name
        type: Exact
        value: {{ .Values.routing.modelName }}
{{- end }}